name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  cloud_firestore: ^3.1.9
  animated_text_kit: 4.2.1
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.8
  modal_progress_hud: 0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
